# Run Chromium in a container
#
# docker run -it \
#	--net host \ # may as well YOLO
#	--cpuset-cpus 0 \ # control the cpu
#	--memory 512mb \ # max memory it can use
#	-v /tmp/.X11-unix:/tmp/.X11-unix \ # mount the X11 socket
#	-e DISPLAY=unix$DISPLAY \
#	-v $HOME/Downloads:/home/chromium/Downloads \
#	-v $HOME/.config/chromium/:/data \ # if you want to save state
#	--security-opt seccomp=$HOME/chrome.json \
#	--device /dev/snd \ # so we have sound
#	-v /dev/shm:/dev/shm \
#	--name chromium \
#	jess/chromium
#
# You will want the custom seccomp profile:
# 	wget https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json -O ~/chrome.json

# Base docker image
FROM debian:bookworm-slim
LABEL maintainer "Jessie Frazelle <jess@linux.com>"

# RUN apt-get update && apt-get install -y wget curl gnupg apt-transport-https ca-certificates\
# gnupg \
# apt-transport-https \
# ca-certificates \
# # wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# # curl -fSsL https://dl-ssl.google.com/linux/linux_signing_key.pub| gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg >> /dev/null \
# curl -fSsL https://dl-ssl.google.com/linux/linux_signing_key.pub| gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg|apt-key adv --keyserver keyserver.ubuntu.com --recv-keys

# Install Chromium
# Yes, including the Google API Keys sucks but even debian does the same: https://packages.debian.org/stretch/amd64/chromium/filelist
 RUN apt-get update && apt-get install -y \
    # chromium \
    # chromium-l10n \
    fonts-liberation \
    fonts-roboto \
    hicolor-icon-theme \
    libcanberra-gtk-module \
    libexif-dev \
    libgl1-mesa-dri \
    libgl1-mesa-glx \
    libpango-1.0-0 \
    libv4l-0 \
    fonts-symbola \
    libcanberra-gtk-module \
    libcanberra-gtk-common-dev \
    libcanberra-gtk3-0 \
    libcanberra-gtk3-module \
    # wait for next step 
    # dbus-x11 \
    #
    # for chrome
    ca-certificates  \
    curl \
    wget \
    gnupg \
    apt-transport-https \
    sudo \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /etc/chromium.d/ \
    && /bin/echo -e 'export GOOGLE_API_KEY="AIzaSyCkfPOPZXDKNn8hhgu3JrA62wIgC93d44k"\nexport GOOGLE_DEFAULT_CLIENT_ID="811574891467.apps.googleusercontent.com"\nexport GOOGLE_DEFAULT_CLIENT_SECRET="kdloedMFGdGla2P1zacGjAQh"' > /etc/chromium.d/googleapikeys

# FROM HERE
# https://linux.how2shout.com/install-google-chrome-on-debian-12-bookworm/

# install chrome key
# RUN curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg >> /dev/null
# with ssl
# RUN curl -fSsL https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg >> /dev/null
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN curl -fSsL https://dl-ssl.google.com/linux/linux_signing_key.pub| gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg|apt-key adv --keyserver keyserver.ubuntu.com --recv-keys

# add chrome to dpkg list
RUN echo deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main | tee /etc/apt/sources.list.d/google-chrome.list

# update package
RUN apt update

RUN apt install --yes google-chrome-stable

# Add chromium user
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video,sudo chrome \
    && mkdir -p /home/chrome/Downloads && chown -R chrome:chrome /home/chrome

# ENV DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

# Run as non privileged user
USER chrome

ENV DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

RUN mkdir /tmp/data

# ENTRYPOINT ["/usr/bin/google-chrome","--no-sandbox"]
# "--disable-gpu","--disable-features=dbus"
ENTRYPOINT ["/usr/bin/google-chrome-stable", \
"--no-sandbox", \
"--disable-gpu", \
"--disable-features=dbus"]
CMD [ "--user-data-dir=/data" ]
